<?php require_once ('Views/template/header.phtml')?>
<div class="row align-items-center" id="login-body">
    <div class="col-sm-1 col-md-2 col-lg-3"></div>
    <div class="col-sm-10 col-md-8 col-lg-6">
        <h1 class="mb-5 display-4 text-center">LOGIN</h1>
<!--        Login form -->
        <form method="post" class="text-center">

            <div class="form-group">
                <input class="form-control" type="email" name="username" placeholder="Email Address" value="<?php if(isset($_POST['username'])){echo $_POST['username'];}?>" required>
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password" value="<?php if(isset($_POST['password'])){echo $_POST['password'];} ?>" required>
            </div>
            <p class="text-danger"><?php if(isset($view->loggedin)){echo $view->loggedin;}?></p>
            <div class="form-group">
                <input class="btn btn-outline-success form-control" name="loginSubmitBtn" type="submit" value="Login">
            </div>

<!--            Display the link to the sign up page-->
            <div class="message">
                <p>Don't have an account yet?<a href="signup.php"> Sign up here</a></p>

            </div>
        </form>

    </div>
    <div class="col-sm-1 col-md-2 col-lg-3">
    </div>

</div>

<?php require_once ("Views/template/footer.phtml"); ?>
